on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    # every Monday
    - cron:  '0 0 * * 1'

name: build

jobs:

  build-x86_64-unknown-linux-musl:
    name: Build x86_64-unknown-linux-musl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target=x86_64-unknown-linux-musl --release --locked
      - run: strip target/x86_64-unknown-linux-musl/release/shell-snoop
      - uses: actions/upload-artifact@v2
        with:
          name: shell-snoop
          path: target/x86_64-unknown-linux-musl/release/shell-snoop
          retention-days: 8
          if-no-files-found: 'error'
